[package]
name = "lemurs"
authors = ["Gijs Burghoorn <me@gburghoorn.com>"]
description = "A TUI Display/Login Manager"
version = "0.4.0"

edition = "2021"

categories = ["gui", "authentication"]
keywords = ["display", "login", "desktop"]

repository = "https://github.com/coastalwhite/lemurs"
homepage = "https://github.com/coastalwhite/lemurs"

readme = "README.md"
license = "MIT or APACHE"

include = [
    "/src",
    "/assets",
    "/README.md",
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
    "/extra"
]

rust-version = "1.84.0"

[dependencies]
# UI and TUI interface
ratatui = "0.29.0"
image = "0.25"
crossterm = "0.26"
unicode-width = "0.1"

# Graphical Backend (Experimental)
drm = "0.14.1"
drm-ffi = "0.9.0"
drm-sys = "0.8.0"
embedded-graphics = "0.8.1"

mio = { version = "0.8.8", features = [ "os-poll", "os-ext" ] }

deentry = "0.0.1"

# Interacting with the kernel interfaces
rand = "0.9"
nix = { version = "0.29", features = ["fs", "user", "process", "term", "signal", "mman"] }

# UTMPX
libc = "0.2"

# Authentication and Fetching User Data
pam = "0.8.0"
uzers = "0.11"

# Once Cell
once_cell = "1.17.1"

# Logging
env_logger = { version = "0.9.0", default-features = false, features = ["humantime"] }
log = "0.4.0"

# Configuration File Parsing
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
secrecy = "0.8"
rusttype = "0.9.3"


# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
